import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const globalStyles = StyleSheet.create({
  contenedorPrincipal: {
    flex: 1,
    backgroundColor: "#121212",
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  seccionEncabezado: {
    marginBottom: 24,
    backgroundColor: "#1e1e1f",
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(200, 178, 119, 0.15)",
  },
  tituloPrincipal: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 6,
  },
  descripcionEncabezado: {
    fontSize: 14,
    color: "#8e8e93",
    lineHeight: 20,
    marginBottom: 8,
  },
  cotizacionesTexto: {
    fontSize: 14,
    color: "#c8b277",
    fontWeight: "600",
    fontStyle: "italic",
    marginTop: 4,
  },
  contenedorBotonesAccion: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 14,
  },
  botonComparativa: {
    backgroundColor: "#c8b277",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 100,
  },
  botonComparativaTexto: {
    color: "#121212",
    fontWeight: "bold",
    fontSize: 13,
  },
  botonArchivar: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#c8b277",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  botonArchivarTexto: {
    color: "#c8b277",
    fontWeight: "bold",
    fontSize: 13,
  },
  tarjetaGeneral: {
    backgroundColor: "#1e1e1f",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  tituloTarjeta: {
    fontSize: 16,
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 16,
  },
  graficoConLeyenda: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  contenedorGraficoPie: {
    width: 130,
    height: 130,
    justifyContent: "center",
    alignItems: "center",
  },
  leyendaGrafico: {
    flex: 1,
    marginLeft: 16,
    gap: 8,
  },
  itemLeyenda: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  circuloColor: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 6,
  },
  leyendaTextoContainer: {
    flex: 1,
  },
  leyendaTexto: {
    color: "#e5e5ea",
    fontSize: 12,
  },
  valorMontoGasto: {
    color: "#ff4b4b",
    fontSize: 13,
    fontWeight: "600",
  },
  valorMontoIngreso: {
    color: "#34c759",
    fontSize: 13,
    fontWeight: "600",
  },
  avisoVacio: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 32,
  },
  iconoPlaceholder: {
    fontSize: 36,
    marginBottom: 8,
  },
  mensajeVacio: {
    color: "#8e8e93",
    fontSize: 14,
    textAlign: "center",
  },
  sugerenciaVacio: {
    color: "#c8b277",
    fontSize: 12,
    marginTop: 4,
    textAlign: "center",
  },
  infoLimitesPlan: {
    backgroundColor: "rgba(0,0,0,0.3)",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(200,178,119,0.2)",
    marginBottom: 16,
  },
  filaProgreso: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  pistaBarra: {
    height: 8,
    backgroundColor: "#2c2c2e",
    borderRadius: 4,
    width: "100%",
    overflow: "hidden",
    marginBottom: 6,
  },
  rellenoBarra: {
    height: "100%",
    backgroundColor: "#c8b277",
  },
  textoMontoProgreso: {
    fontSize: 12,
    color: "#8e8e93",
  },
  tarjetaAhorroItem: {
    backgroundColor: "#1e1e1f",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  botonEditarAhorro: {
    alignSelf: "flex-end",
    backgroundColor: "rgba(200,178,119,0.1)",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    marginTop: 10,
  },
  botonEditarAhorroTexto: {
    color: "#c8b277",
    fontSize: 12,
    fontWeight: "600",
  },
  tarjetaLogro: {
    backgroundColor: "#1e1e1f",
    borderWidth: 1,
    borderColor: "rgba(200, 178, 119, 0.4)",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  capaModal: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.75)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  contenidoModal: {
    backgroundColor: "#1e1e1f",
    borderRadius: 14,
    padding: 20,
    width: "100%",
    borderWidth: 1,
    borderColor: "rgba(200,178,119,0.3)",
  },
  formularioGrupo: {
    marginBottom: 14,
  },
  labelForm: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 6,
  },
  inputForm: {
    backgroundColor: "#2c2c2e",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    color: "#ffffff",
    fontSize: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  inputSelectContainer: {
    backgroundColor: "#2c2c2e",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    overflow: "hidden",
  },
  pickerNativo: {
    color: "#ffffff",
    width: "100%",
  },
  formularioAcciones: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 16,
  },
  botonModalPrimario: {
    backgroundColor: "#c8b277",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  botonModalSecundario: {
    backgroundColor: "#3a3a3c",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  botonModalEliminar: {
    backgroundColor: "#dc3545",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginRight: "auto",
  },
  toastBanner: {
    position: "absolute",
    top: 40,
    left: 16,
    right: 16,
    borderRadius: 8,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    zIndex: 9999,
    elevation: 6,
  },
  toastTexto: {
    color: "#ffffff",
    fontWeight: "600",
    fontSize: 13,
  }
});