import { StyleSheet } from "react-native";

export const planesStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#121212", paddingHorizontal: 20, paddingTop: 20 },
  centerLoading: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "#121212" },
  textoCargando: { color: "#c8b277", marginTop: 10, fontSize: 16 },
  bannerUsuario: { backgroundColor: "#1e1e1f", padding: 12, borderRadius: 8, marginBottom: 15, borderWidth: 1, borderColor: "#c8b277", alignItems: "center" },
  textoBanner: { color: "#aaa", fontSize: 13 },
  rolResaltado: { color: "#c8b277", fontWeight: "bold" },
  introduccion: { color: "#aaa", fontSize: 14, textAlign: "center", marginBottom: 25, lineHeight: 20 },
  selectorSuscripcion: { flexDirection: "row", backgroundColor: "#1e1e1f", borderRadius: 8, padding: 4, marginBottom: 30, borderWidth: 1, borderColor: "#333" },
  tabBoton: { flex: 1, paddingVertical: 12, alignItems: "center", borderRadius: 6 },
  tabActivo: { backgroundColor: "#c8b277" },
  tabTexto: { color: "#fff", fontSize: 15, fontWeight: "600" },
  tabTextoActivo: { color: "#121212", fontWeight: "700" },
  tarjetaPlan: { backgroundColor: "#1e1e1f", borderRadius: 12, padding: 20, marginBottom: 25, borderWidth: 1, borderColor: "#333" },
  tarjetaActiva: { borderColor: "#c8b277", borderWidth: 1.5 },
  contenidoSuperior: { flex: 1 },
  badgeSuscripcion: { backgroundColor: "#333", color: "#c8b277", paddingVertical: 4, paddingHorizontal: 10, borderRadius: 4, fontSize: 12, fontWeight: "bold" },
  badgePlanActual: { backgroundColor: "#c8b277", color: "#121212", paddingVertical: 4, paddingHorizontal: 10, borderRadius: 4, fontSize: 11, fontWeight: "bold" },
  planNombre: { color: "#fff", fontSize: 22, fontWeight: "bold", textAlign: "center", marginBottom: 5 },
  planPrecio: { color: "#c8b277", fontSize: 26, fontWeight: "bold", textAlign: "center", marginBottom: 20 },
  listaDetalles: { marginVertical: 15 },
  itemDetalle: { fontSize: 14, lineHeight: 22, marginBottom: 8 },
  detalleIncluido: { color: "#e0e0e0" },
  detalleExcluido: { color: "#888", textDecorationLine: "line-through" },
  detalleDestacado: { color: "#c8b277", fontWeight: "600" },
  detalleNormal: { color: "#ccc" },
  detalleVacio: { color: "#666", fontStyle: "italic", textAlign: "center" },
  contenedorBoton: { marginTop: 15, minHeight: 48 },
  btnPlan: { paddingVertical: 14, borderRadius: 8, alignItems: "center", justifyContent: "center" },
  btnPlanSuscribir: { backgroundColor: "#c8b277" },
  btnDeshabilitado: { backgroundColor: "#2d2d2d" },
  btnTexto: { color: "#121212", fontSize: 16, fontWeight: "bold" }
});