import { StyleSheet } from "react-native";

export const administrarMovimientoStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0F1015', paddingHorizontal: 16 },
  btnCerrarText: { color: '#FFFFFF', fontWeight: '700', textAlign: 'center' },
  headerTabs: { flexDirection: 'row', marginTop: 16, marginBottom: 12, borderRadius: 16, backgroundColor: '#1C1C1E', padding: 6 },
  tab: { flex: 1, paddingVertical: 12, alignItems: 'center', justifyContent: 'center', borderRadius: 12 },
  tabActive: { backgroundColor: '#2C2C2E', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 4, elevation: 2 },
  tabText: { color: '#7C818C', fontWeight: '600', letterSpacing: 0.5, fontSize: 13 },
  tabTextActive: { color: '#FFFFFF', fontWeight: 'bold' },
  cotizacionesBox: { alignItems: 'center', marginBottom: 16 },
  cotizacionesText: { color: '#7C818C', fontSize: 12, fontWeight: '600', letterSpacing: 0.3 },
  resumenContainer: { backgroundColor: '#1C1C1E', borderRadius: 20, padding: 24, marginBottom: 20, borderTopWidth: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.25, shadowRadius: 10, elevation: 8 },
  resumenLabel: { color: '#9BA1A6', fontSize: 13, textAlign: 'center', marginBottom: 8, textTransform: 'uppercase', letterSpacing: 1, fontWeight: '600' },
  resumenTotal: { color: '#FFFFFF', fontSize: 36, fontWeight: '900', textAlign: 'center', letterSpacing: -1 },
  inputBusqueda: { backgroundColor: '#252528', color: '#FFFFFF', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 14, fontSize: 15, marginTop: 20 },
  cardItem: { backgroundColor: '#1C1C1E', borderRadius: 16, padding: 18, marginBottom: 14, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 8, elevation: 4 },
  cardInfo: { flex: 1, paddingRight: 12 },
  cardTitulo: { color: '#FFFFFF', fontSize: 16, fontWeight: '700', marginBottom: 6, letterSpacing: 0.2 },
  cardFecha: { color: '#9BA1A6', fontSize: 13, fontWeight: '500' },
  cardDerecha: { alignItems: 'flex-end' },
  contenedorMontos: { alignItems: 'flex-end', marginBottom: 12 },
  cardMonto: { fontSize: 17, fontWeight: '800', letterSpacing: -0.5 },
  cardMontoConvertido: { fontSize: 11, color: '#7C818C', marginTop: 4, fontWeight: '500' },
  cardAcciones: { flexDirection: 'row', gap: 18 },
  iconBtn: { fontSize: 17 },
  emptyText: { color: '#7C818C', textAlign: 'center', marginTop: 40, fontSize: 16, fontWeight: '500' },
  fab: { position: 'absolute', bottom: 32, right: 24, width: 64, height: 64, borderRadius: 32, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.35, shadowRadius: 10, elevation: 10 },
  fabText: { color: '#FFFFFF', fontSize: 32, fontWeight: '300', marginTop: -4 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.75)', justifyContent: 'center', padding: 20 },
  modalContent: { backgroundColor: '#1C1C1E', borderRadius: 24, padding: 24, maxHeight: '90%', borderTopWidth: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.4, shadowRadius: 15, elevation: 15 },
  modalTitle: { color: '#FFFFFF', fontSize: 22, fontWeight: '800', textAlign: 'center', marginBottom: 24, letterSpacing: 0.5 },
  inputLabel: { fontSize: 12, fontWeight: '700', marginBottom: 8, marginTop: 18, textTransform: 'uppercase', letterSpacing: 1 },
  input: { backgroundColor: '#252528', color: '#FFFFFF', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 14, fontSize: 16, borderWidth: 1, borderColor: '#333336' },
  charCount: { color: '#7C818C', fontSize: 11, textAlign: 'right', marginTop: 6, fontWeight: '500' },
  selectorBtn: { backgroundColor: '#252528', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 16, borderWidth: 1, borderColor: '#333336' },
  selectorText: { color: '#FFFFFF', fontSize: 16, fontWeight: '500' },
  modalActions: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 32, gap: 12 },
  btnSecondary: { flex: 1, paddingVertical: 16, borderRadius: 12, backgroundColor: '#2C2C2E', alignItems: 'center' },
  btnSecondaryText: { color: '#FFFFFF', fontWeight: '700', letterSpacing: 0.5 },
  btnPrimary: { flex: 1, paddingVertical: 16, borderRadius: 12, alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 5, elevation: 4 },
  btnPrimaryText: { color: '#FFFFFF', fontWeight: '800', letterSpacing: 0.5, textTransform: 'uppercase' },
  detalleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#2C2C2E' },
  detalleLabel: { color: '#9BA1A6', fontSize: 15, fontWeight: '500' },
  detalleValor: { color: '#FFFFFF', fontSize: 15, fontWeight: '600', flexShrink: 1, textAlign: 'right', marginLeft: 15 },
  pickerContainer: { backgroundColor: '#1C1C1E', position: 'absolute', bottom: 0, left: 0, right: 0, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 24, maxHeight: '60%', shadowColor: '#000', shadowOffset: { width: 0, height: -5 }, shadowOpacity: 0.3, shadowRadius: 10, elevation: 20 },
  pickerTitle: { color: '#FFFFFF', fontSize: 18, fontWeight: '800', marginBottom: 20, textAlign: 'center', letterSpacing: 0.5 },
  pickerItem: { paddingVertical: 18, borderBottomWidth: 1, borderBottomColor: '#2C2C2E', borderRadius: 8 },
  pickerItemText: { color: '#FFFFFF', fontSize: 16, textAlign: 'center', fontWeight: '500' }
});