import { StyleSheet } from "react-native";

export const archivosStyles = StyleSheet.create({
  filtrosRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 16, gap: 12 },
  pickerWrapperFiltro: { flex: 1, backgroundColor: "#ffffff", borderRadius: 12, borderWidth: 1, borderColor: "rgba(200,178,119,0.2)", overflow: "hidden" },
  tabsContenedor: { flexDirection: "row", backgroundColor: "#1e1e1f", borderRadius: 12, padding: 4, marginBottom: 20, borderWidth: 1, borderColor: "rgba(200,178,119,0.2)" },
  tabBoton: { flex: 1, paddingVertical: 12, alignItems: "center", borderRadius: 8 },
  tabBotonActivo: { backgroundColor: "#c8b277" },
  tabTexto: { color: "#8e8e93", fontSize: 14, fontWeight: "600" },
  tabTextoActivo: { color: "#121212", fontWeight: "bold" },
  tarjetaArchivo: { backgroundColor: "#1e1e1f", borderRadius: 16, padding: 16, marginBottom: 16, borderWidth: 1, borderColor: "rgba(200,178,119,0.2)" },
  archivoPreviewCaja: { height: 140, width: "100%", borderRadius: 12, backgroundColor: "#2c2c2e", justifyContent: "center", alignItems: "center", marginBottom: 16, overflow: "hidden" },
  archivoImagen: { width: "100%", height: "100%", resizeMode: "cover" },
  archivoDetalles: { marginBottom: 16 },
  archivoTitulo: { color: "#ffffff", fontSize: 16, fontWeight: "bold", marginBottom: 6 },
  archivoRef: { color: "#c8b277", fontSize: 13, marginBottom: 4, fontWeight: "500" },
  archivoAcciones: { flexDirection: "row", justifyContent: "space-between", gap: 12 },
  movimientoFecha: { color: "#8e8e93", fontSize: 12 },
  botonDescargaArchivos: { flex: 1, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: "#c8b277", alignItems: "center" },
  textoDescarga: { color: "#c8b277", fontWeight: "600", fontSize: 12 },
  botonModalEliminarArchivos: { flex: 1, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: "#ff4b4b", backgroundColor: "#3a3a3a", alignItems: "center" },
  textoEliminar: { color: "#c8b277", fontWeight: "bold", fontSize: 12 },
  bloqueoContenedor: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "#121212", padding: 20 },
  bloqueoTarjeta: { backgroundColor: "#1e1e1f", borderRadius: 24, padding: 32, alignItems: "center", borderColor: "rgba(200,178,119,0.3)", borderWidth: 1, width: "100%" },
  botonArchivar: { backgroundColor: "transparent", borderWidth: 1, borderColor: "#c8b277", paddingVertical: 10, paddingHorizontal: 16, borderRadius: 8, width: "100%", alignItems: "center", marginTop: 4 },
  botonArchivarTexto: { color: "#c8b277", fontWeight: "bold", fontSize: 14 },
  capaModal: { flex: 1, backgroundColor: "rgba(0,0,0,0.8)", justifyContent: "center", alignItems: "center", padding: 20 },
  contenidoModal: { backgroundColor: "#1e1e1f", width: "100%", borderRadius: 16, padding: 24, borderWidth: 1, borderColor: "rgba(200,178,119,0.3)" },
  tituloTarjeta: { fontSize: 18, fontWeight: "bold", color: "#ffffff", marginBottom: 16 },
  formularioGrupo: { marginBottom: 16 },
  labelForm: { color: "#ffffff", fontSize: 13, marginBottom: 6, fontWeight: "600" },
  inputSelectContainer: { backgroundColor: "#2c2c2e", borderRadius: 8, overflow: "hidden" },
  pickerNativo: { color: "#ffffff", backgroundColor: "#2c2c2e" },
  inputForm: { backgroundColor: "#2c2c2e", borderRadius: 8, padding: 12, color: "#ffffff", fontSize: 15 },
  formularioAccionesVincularArchivo: { flexDirection: "row", justifyContent: "space-between", marginTop: 25, gap: 12 },
  botonModalCancelarArchivo: { flex: 1, paddingVertical: 14, borderRadius: 10, borderWidth: 1.5, borderColor: "#ff4b4b", alignItems: "center", justifyContent: "center" },
  botonModalSubirArchivo: { flex: 1, paddingVertical: 14, borderRadius: 10, backgroundColor: "#c8b277", alignItems: "center", justifyContent: "center" },
  textoBotonCancelar: { color: "#c8b277", fontWeight: "bold", fontSize: 15 },
  textoBotonSubir: { color: "#121212", fontWeight: "bold", fontSize: 15 },
  container: { flex: 1, backgroundColor: "#121212" },
  card: { backgroundColor: "#1e1e1e", borderRadius: 16, padding: 16, marginBottom: 16, borderWidth: 1, borderColor: "#2a2a2a", shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 6, elevation: 3 },
  scrollContent: { padding: 20, paddingBottom: 60 },
  centerContainer: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "#121212", padding: 20 },
  loadingText: { color: "#a0a0a0", marginTop: 16, fontSize: 16 },
  headerSection: { marginBottom: 24, marginTop: 10 },
  headerTitle: { fontSize: 28, fontWeight: "bold", color: "#c8b277", marginBottom: 6, letterSpacing: 0.5 },
  headerSubtitle: { fontSize: 15, color: "#a0a0a0" },
  pickerContainer: { flex: 1, backgroundColor: "#1e1e1e", borderRadius: 12, borderWidth: 1, borderColor: "#333", overflow: "hidden", height: 50, justifyContent: "center" },
  picker: { color: "#fff", width: "100%" },
  btnPrimary: { backgroundColor: "#c8b277", paddingVertical: 16, borderRadius: 12, alignItems: "center", marginBottom: 24, shadowColor: "#c8b277", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 8, elevation: 5 },
  btnPrimaryText: { color: "#121212", fontSize: 16, fontWeight: "bold", letterSpacing: 0.3 },
  tabsContainer: { flexDirection: "row", backgroundColor: "#1e1e1e", borderRadius: 12, padding: 4, marginBottom: 20 },
  tabButton: { flex: 1, paddingVertical: 12, borderRadius: 10, alignItems: "center" },
  tabButtonActive: { backgroundColor: "#333" },
  tabText: { color: "#8e8e93", fontSize: 15, fontWeight: "600" },
  tabTextActive: { color: "#c8b277" },
  listContainer: { flex: 1 },
  emptyState: { padding: 30, alignItems: "center", backgroundColor: "#1e1e1e", borderRadius: 16, borderStyle: "dashed", borderWidth: 1, borderColor: "#333" },
  emptyStateText: { color: "#8e8e93", fontSize: 15, textAlign: "center" },
  cardContent: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  thumbnailContainer: { marginRight: 16 },
  thumbnailImage: { width: 56, height: 56, borderRadius: 10, backgroundColor: "#2a2a2a" },
  thumbnailGeneric: { width: 56, height: 56, borderRadius: 10, backgroundColor: "#2a2a2a", justifyContent: "center", alignItems: "center", borderWidth: 1, borderColor: "#333" },
  thumbnailText: { color: "#c8b277", fontWeight: "bold", fontSize: 14 },
  cardDetails: { flex: 1 },
  cardTitle: { color: "#fff", fontSize: 16, fontWeight: "600", marginBottom: 4 },
  cardSubtitle: { color: "#a0a0a0", fontSize: 13, marginBottom: 4 },
  cardDate: { color: "#c8b277", fontSize: 12, fontWeight: "500" },
  cardActions: { flexDirection: "row", justifyContent: "flex-end", gap: 12, borderTopWidth: 1, borderTopColor: "#2a2a2a", paddingTop: 12 },
  btnSecondary: { paddingVertical: 8, paddingHorizontal: 16, borderRadius: 8, backgroundColor: "rgba(200, 178, 119, 0.1)" },
  btnSecondaryText: { color: "#c8b277", fontSize: 13, fontWeight: "600" },
  btnDanger: { paddingVertical: 8, paddingHorizontal: 16, borderRadius: 8, backgroundColor: "rgba(255, 69, 58, 0.1)" },
  btnDangerText: { color: "#ff453a", fontSize: 13, fontWeight: "600" },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0, 0, 0, 0.7)", justifyContent: "center", alignItems: "center", padding: 20 },
  modalCard: { backgroundColor: "#1e1e1e", width: "100%", maxWidth: 400, borderRadius: 20, padding: 24, borderWidth: 1, borderColor: "#333" },
  modalTitle: { fontSize: 20, fontWeight: "bold", color: "#c8b277", marginBottom: 20, textAlign: "center" },
  formGroup: { marginBottom: 16 },
  formLabel: { color: "#a0a0a0", fontSize: 13, marginBottom: 8, fontWeight: "500" },
  fileDropZone: { borderWidth: 1.5, borderStyle: "dashed", borderColor: "#c8b277", borderRadius: 12, paddingVertical: 20, paddingHorizontal: 16, alignItems: "center", backgroundColor: "rgba(200, 178, 119, 0.05)" },
  fileDropText: { color: "#8e8e93", fontSize: 14, textAlign: "center" },
  fileDropTextActive: { color: "#fff", fontSize: 14, fontWeight: "600", textAlign: "center" },
  modalActions: { flexDirection: "row", justifyContent: "space-between", gap: 12, marginTop: 24 },
  btnModalCancel: { flex: 1, paddingVertical: 14, borderRadius: 10, backgroundColor: "#2a2a2a", alignItems: "center" },
  btnModalCancelText: { color: "#fff", fontWeight: "600", fontSize: 15 },
  btnModalSubmit: { flex: 1, paddingVertical: 14, borderRadius: 10, backgroundColor: "#c8b277", alignItems: "center" },
  btnModalSubmitText: { color: "#121212", fontWeight: "bold", fontSize: 15 },
  premiumCard: { backgroundColor: "#1e1e1e", borderRadius: 20, padding: 30, alignItems: "center", borderWidth: 1, borderColor: "#c8b277", width: "100%" },
  iconContainer: { backgroundColor: "rgba(200, 178, 119, 0.1)", padding: 20, borderRadius: 50, marginBottom: 20 },
  lockIcon: { fontSize: 40 },
  premiumTitle: { color: "#c8b277", fontSize: 22, fontWeight: "bold", marginBottom: 12 },
  premiumText: { color: "#a0a0a0", textAlign: "center", fontSize: 15, lineHeight: 22, marginBottom: 24 },
  btnPremium: { backgroundColor: "#c8b277", width: "100%", paddingVertical: 16, borderRadius: 12, alignItems: "center", marginBottom: 12 },
  btnPremiumText: { color: "#121212", fontSize: 16, fontWeight: "bold" },
  btnBack: { paddingVertical: 12 },
  btnBackText: { color: "#8e8e93", fontSize: 15, fontWeight: "600" },
  errorCard: { backgroundColor: "#1e1e1e", borderRadius: 16, padding: 24, width: "100%", alignItems: "center", borderWidth: 1, borderColor: "#ff453a" },
  errorTitle: { color: "#ff453a", fontSize: 20, fontWeight: "bold", marginBottom: 12 },
  errorText: { color: "#a0a0a0", textAlign: "center", marginBottom: 24 }
});